const apiUrl = ""
const eventEntryTemplate = document.querySelector("#eventEntryTemplate")
const eventInfoContainer = document.getElementById("eventInfoContainer")
debug = true



function switchPanel(panel) {
	
	document.querySelectorAll(".panel1").forEach(function (p) {
		p.classList.add("hidden");
	});
	document.getElementById(panel).classList.remove("hidden");
}

function switchPanelFromMenu(obj, panel) {
	document.querySelectorAll(".menuEntry").forEach(function (p) {
		p.classList.remove("menuEntryActive");
	});
	obj.classList.add("menuEntryActive");
	switchPanel(panel);
}

function openEventPage(eventthis, from) {
	console.info(eventthis.children[0].innerText)
	switchPanel("EventInfo")
	eventInfoContainer.innerHTML = eventthis.innerHTML
}

async function getEvents() {
	const query = document.getElementById("search")
	try {
		const data = await getEventsData(query.value)
		if (!data) return
		if (data.results.length <= 0) return
		console.log(data)

		results = data.results;

		const eventList = document.getElementById("eventList");
		eventList.innerHTML = ""
		for (const res of results) {
			eventList.appendChild(insertEvent(res))
		}
	} catch (error) {
		console.error('Search failed:', error)
	}
}

async function getEventsData(query) {
	lastDataS = localStorage.getItem("lastDataSync") * 1

	console.log(lastDataS + 10000)
	console.log(Date.now())


	if (lastDataS + 10000 > Date.now()) {
		console.info("Last request < 10 sec => Using localstorage")
		return JSON.parse(localStorage.getItem("eventData"))
	}

	if (debug) {
		console.info("Using debug data")
		localStorage.setItem("lastDataSync", Date.now())
		return unholyDebugData
	}

	const params = new URLSearchParams();
	params.append('q', query);

	let url = api + "/events/search?" + params.toString();
	console.log("Request URL:", url);

	try {
		const response = await fetch(url);eventView

		localStorage.setItem("lastDataSync", Date.now())

		return data;
	} catch (error) {
		console.error(error.message);
		throw error;
	}
}

function insertEvent(event) {
	const toInsert = eventEntryTemplate.content.cloneNode(true);
	eventEntry = toInsert.childNodes[1]
	eventEntry.children[0].innerText = event.title
	eventEntry.children[1].innerText = event.date
	eventEntry.children[2].innerText = event.location.name
	eventEntry.children[3].innerText = event.location.address
	eventEntry.children[4].innerText = event.price

	return toInsert
}


const unholyDebugData = { //this example data was generated by slavery (copilot)
	results: [
		{
			title: "Babymetal Live",
			date: "2023-10-11",
			location: {
				name: "Olypmiastadion München",
				address: "1234 Main St, Munich",
				lat: 48.1351,
				long: 11.5820
			},
			price: "69€"
		},
		{
			title: "Rock Concert",
			date: "2023-11-05",
			location: {
				name: "Arena Berlin",
				address: "Konzerthausplatz 1, Berlin",
				lat: 52.5200,
				long: 13.4050
			},
			price: "59€"
		},
		{
			title: "Jazz Night",
			date: "2023-12-01",
			location: {
				name: "Jazz Club Frankfurt",
				address: "12 Street, Frankfurt",
				lat: 50.1109,
				long: 8.6821
			},
			price: "49€"
		},
		{
			title: "Indie Fest",
			date: "2023-10-20",
			location: {
				name: "Sunset Park",
				address: "45 Grove Ave, Hamburg",
				lat: 53.5511,
				long: 9.9937
			},
			price: "39€"
		},
		{
			title: "Electro Party",
			date: "2023-11-15",
			location: {
				name: "Club Neon",
				address: "89 Beat Blvd, Cologne",
				lat: 50.9375,
				long: 6.9603
			},
			price: "45€"
		},
		{
			title: "Classical Evening",
			date: "2023-12-10",
			location: {
				name: "Grand Theater",
				address: "100 Symphony Ln, Stuttgart",
				lat: 48.7758,
				long: 9.1829
			},
			price: "75€"
		},
		{
			title: "Folk Fair",
			date: "2024-01-05",
			location: {
				name: "Village Hall",
				address: "22 Country Rd, Bremen",
				lat: 53.0793,
				long: 8.8017
			},
			price: "25€"
		},
		{
			title: "Hip Hop Jam",
			date: "2024-01-20",
			location: {
				name: "Urban Stage",
				address: "57 Street Art Ave, Dresden",
				lat: 51.0504,
				long: 13.7373
			},
			price: "55€"
		},
		{
			title: "Metal Mayhem",
			date: "2024-02-14",
			location: {
				name: "Cave Club",
				address: "77 Rock Road, Düsseldorf",
				lat: 51.2277,
				long: 6.7735
			},
			price: "65€"
		},
		{
			title: "Pop Extravaganza",
			date: "2024-03-01",
			location: {
				name: "City Arena",
				address: "33 Celebration St, Leipzig",
				lat: 51.3397,
				long: 12.3731
			},
			price: "85€"
		}
	]
}

localStorage.setItem("eventData", JSON.stringify(unholyDebugData))

document.getElementById("search").addEventListener("input", function () {
	let query = this.value.toLowerCase();
	Array.from(document.getElementById("eventList").children).forEach(function (child) {
		if (child.children[0].innerText.toLowerCase().includes(query)) {
			child.style.display = "grid";
		} else {
			child.style.display = "none";
		}
	});
});

